### ISSUE TITLE
Use bls12-381 keygen

### ISSUE THREAD

**Issue by paulmillr** [iancoleman/eip2333-tool#1]
Hey.

I've made https://github.com/paulmillr/bls12-381-keygen. You should use it instead of `@chainsafe/bls-hd-key` because it uses just one dependency. It would reduce package size massively.

Its readme contains sample code that you can copy-paste.

Also `buffer` dep you're using is not really needed.

**Comment by iancoleman** [comment]
Good tip thanks! See https://github.com/iancoleman/eip2333-tool/commit/640efbf8d5a6158d0c029f78cc5fa9d93b589980
