### ISSUE TITLE
Mnemonic gives invalid master secret key, 63 chars

### ISSUE THREAD

**Issue by iancoleman** [iancoleman/eip2333-tool#2]
Steps to reproduce:

* Enter mnemonic `enough fever tattoo rich walnut engage spin course example witness loan exhaust retire always brush`
* Copy master secret key `73427a557244603962453d4c3971646d560333a0d1518619399419e006c34b`
* Note only 63 chars, should be 64
* Paste into https://iancoleman.io/threshold_crypto_ui
* See it fails to generate a public key

Not sure why the master secret key is one character short.

It's not a leading 0 as the missing char in master secret keys, eg there's a leading zero in the master secret key for `meat nation add position eight delay grunt wrap nut deputy street island left elegant fiber`

Adding a trailing 0 padding produces the same master public key, but only here (not in threshold_crypto_ui).

Correcting the master secret key with a trailing zero:
`73427a557244603962453d4c3971646d560333a0d1518619399419e006c34b0`
master public key here is
`8a61188ada7de64fbd4960fe26bb44190cf8780ea1fd4517a7cfd04746ae326b318b7b03cc9b909d854f5b5f0f62ee63`
public key in threshold_crypto_ui is
`99bcd9b7c72e4f4efde93375de15c87d4d77310edbd9a0d5328ec72f08581faee5846674114191c2e32766dccaae47c2`

Why is there this discrepancy?

**Comment by paulmillr** [comment]
@iancoleman it's 64 chars for me. Sec begins not with 734, but with 00734. Using Safari.

**Comment by iancoleman** [comment]
Fixed, see related commits:

https://github.com/iancoleman/eip2333-tool/commit/229aa4cfd17daccffe055b582e7cd2ecbec1adc9

https://github.com/iancoleman/eip2333-tool/commit/4f563d90d3f10d944e34bcf070a3a367bd32b6c3

https://github.com/iancoleman/eip2333-tool/commit/b38a8a6f2689d19c5406b7407b4b5ee79314322b

**Comment by paulmillr** [comment]
@iancoleman a quick heads-up -- site doesn't seem to be updated yet

**Comment by paulmillr** [comment]
I mean this:

```
The list of all dependencies of those libraries can be found in libs/package-lock.json

paulmillr/bls12-381-keygen 0.1.2

bitcoinjs/bip39 3.0.3

paulmillr/noble-bls12-381 0.9.0
```

**Comment by iancoleman** [comment]
Ah thanks, good catch. I think better to remove the versions from there, the link to package.json and a list of the libraries (without versions) is enough info. I'll do that now.
