### ISSUE TITLE
Bip39 mnemonic phrase not correctly normalized / sanitized

### ISSUE THREAD

**Issue by loupiote** [iancoleman/eip2333-tool#7]
The bip39 mnemonic phrase not correctly normalized / sanitized in the EIP2333 web tool https://iancoleman.io/eip2333/ .

For example, adding a trailing space (or new-line) after the last word on the "BIP39 Mnemonic" field causes the tool to generate a completely different BIP39 seed, therefore completely different keys.

Same issue when adding extra spaces between the words, etc.

Note that this bug does NOT exist in the classic bip39 web tool https://iancoleman.io/bip39/

**Comment by iancoleman** [comment]
Thanks for this @loupiote

**Comment by loupiote** [comment]
@iancoleman bug is not fully fixed:

adding an extra space (or new-line) between the seed words (e.g. 2 or more spaces or new line between words) causes the seed to change. it should not (no such issue with the ian coleman bip39 tool).

any word separator(s) should all be internally converted into just 1 space.

the current fix only applies to leading / trailing space (or new-line).

example of equivalent seed phrases:

"all all all"

"all    &nbsp;all all"

"all

&nbsp;&nbsp;all  all"

etc
